### ISSUE TITLE
Unable to use LazyImg component in another module

### ISSUE THREAD

**Issue by manishoswal** [malvarezhcr/offline-ionic-2#1]
How do we share this component across module ?

**Comment by marianocodes** [comment]
Hi @manishoswal - sorry the late answer. I'll update the project to work with module. So the lazy component and directive can be imported into other modules

**Comment by manishoswal** [comment]
@mahcr  - You can close this issue. I was able to do it .  However i am getting another issue now after i have installed  cordova-plugin-ionic-webview on ios app. 
"Unsupported URL issue on WKWebView"

**Comment by marianocodes** [comment]
Hi @manishoswal so sorry for the late response, I've update the whole example and made it work in reactive way. Also blog post has been updated as well. I added support to WKWebview.
https://medium.com/ninjadevs/caching-images-ionic-ccf2f4ca8d1f

Let me know if you run into a new issue.
